package: push_it
version: '1.0.0-beta3'
author: 'Thomas Skerbis, Friends Of REDAXO'
supportpage: 'https://github.com/FriendsOfREDAXO/push_it'
title: translate:pushit_title
description: translate:pushit_description

requires:
    redaxo: '^5.19'
    php:
        version: '^8.2'
        
conflicts:
    url: '<2.2.0'  # URL-AddOn < 2.2.0 verwendet inkompatible Riimu\Kit\UrlParser\Uri ohne PSR-7 Return-Types
    
page:
    title: translate:pushit_title
    perm: push_it[]
    icon: rex-icon fa-bell
    subpages:
        settings:
            title: translate:pushit_settings
            perm: admin
        subscriptions:
            title: translate:pushit_subscriptions
            perm: push_it[]
        send:
            title: translate:pushit_send
            perm: push_it[]
        history:
            title: translate:pushit_history
            perm: push_it[]
        backend_notify:
            title: translate:pushit_backend_notify
            perm: push_it[]
        help:
            title: translate:pushit_help
            icon: rex-icon fa-question-circle
            subPath: README.md
            itemClass: 'pull-right'
            perm: push_it[]
        examples:
            title: translate:pushit_examples
            icon: rex-icon fa-code
            subPath: EXAMPLES.md
            itemClass: 'pull-right'
            perm: admin
        api:
            title: translate:pushit_api_reference
            icon: rex-icon fa-book
            subPath: API.md
            itemClass: 'pull-right'
            perm: admin

translate:
    - de_de
    - en_gb

default_config:
    subject: 'mailto:info@example.com'
    publicKey: ''
    privateKey: ''
    backend_enabled: true
    frontend_enabled: true
    admin_notifications: true
