package: push_it
version: '1.0.0-alpha2'
author: 'Thomas Skerbis, Friends Of REDAXO'
supportpage: 'https://github.com/FriendsOfREDAXO/push_it'
title: 'PushIt - Web Push Notifications'
description: 'Web Push Notifications für Frontend und Backend'

requires:
    redaxo: '^5.15'
    php:
        version: '^8.0'
        
conflicts:
    url: '<2.2.0'  # URL-AddOn < 2.2.0 verwendet inkompatible Riimu\Kit\UrlParser\Uri ohne PSR-7 Return-Types
    
page:
    title: 'PushIt'
    perm: push_it[]
    icon: rex-icon fa-bell
    subpages:
        settings:
            title: 'Einstellungen'
            perm: admin
        subscriptions:
            title: 'Subscriptions'
            perm: push_it[]
        send:
            title: 'Senden'
            perm: push_it[]
        history:
            title: 'Verlauf'
            perm: push_it[]
        backend_notify:
            title: 'Backend Benachrichtigungen'
            perm: push_it[]
        help:
            title: 'Hilfe'
            icon: rex-icon fa-question-circle
            subPath: README.md
            itemClass: 'pull-right'
            perm: push_it[]

default_config:
    subject: 'mailto:info@example.com'
    publicKey: ''
    privateKey: ''
    backend_enabled: true
    frontend_enabled: true
    admin_notifications: true
